// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy-DbBErztrggjaPe1e1Pl_VdPEq1nBAc',
    appId: '1:792331991989:web:f7d176a3e6227dfea437fc',
    messagingSenderId: '792331991989',
    projectId: 'erp-task-9453c',
    authDomain: 'erp-task-9453c.firebaseapp.com',
    storageBucket: 'erp-task-9453c.firebasestorage.app',
    measurementId: 'G-6TWBPXSSTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV9TdT4JemzJfzWFMQoDL9oDtAc9y6Glk',
    appId: '1:792331991989:android:3965b6838d50bf65a437fc',
    messagingSenderId: '792331991989',
    projectId: 'erp-task-9453c',
    storageBucket: 'erp-task-9453c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUY20uwhJwE_G2fVJupZvoxprUaf_7U8c',
    appId: '1:792331991989:ios:dbfb6cf838eebe1da437fc',
    messagingSenderId: '792331991989',
    projectId: 'erp-task-9453c',
    storageBucket: 'erp-task-9453c.firebasestorage.app',
    iosClientId: '792331991989-im52718o0rl2avm6onhiq9rpufav62aj.apps.googleusercontent.com',
    iosBundleId: 'com.example.erpTassk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUY20uwhJwE_G2fVJupZvoxprUaf_7U8c',
    appId: '1:792331991989:ios:dbfb6cf838eebe1da437fc',
    messagingSenderId: '792331991989',
    projectId: 'erp-task-9453c',
    storageBucket: 'erp-task-9453c.firebasestorage.app',
    iosClientId: '792331991989-im52718o0rl2avm6onhiq9rpufav62aj.apps.googleusercontent.com',
    iosBundleId: 'com.example.erpTassk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy-DbBErztrggjaPe1e1Pl_VdPEq1nBAc',
    appId: '1:792331991989:web:7a2b450b6d1a69d1a437fc',
    messagingSenderId: '792331991989',
    projectId: 'erp-task-9453c',
    authDomain: 'erp-task-9453c.firebaseapp.com',
    storageBucket: 'erp-task-9453c.firebasestorage.app',
    measurementId: 'G-WN9WYTE0C1',
  );

}